using System.Collections.Generic;

namespace Game.Core.Ecs.Components
{
    /// <summary>
    /// Матч-счётчики на entity игрока (инкрементит MatchCounterTrackerSystem). Измерения:
    ///   CountsByModelId     — РАЗЫГРАНО карт по ModelId (Позвать рой);
    ///   DrawnByModelId      — ВЗЯТО карт по ModelId (Вонючее облако);
    ///   GeneratedByModelId  — СОЗДАНО/ЗАМЕШАНО карт этим игроком по ModelId (Гнидальф);
    ///   InvokedByArchetype  — ПРИЗВАНО существ по ключу архетипа (Грыз: "Imp").
    /// Синк не нужен: события (CardPlayed/Drawn/Generated/CreatureInvoked) идут на обоих клиентах → счётчики зеркальны.
    /// </summary>
    public struct MatchCounterComponent
    {
        public Dictionary<int, int> CountsByModelId;       // played
        public Dictionary<int, int> DrawnByModelId;        // drawn
        public Dictionary<int, int> GeneratedByModelId;    // generated by this player
        public Dictionary<string, int> InvokedByArchetype; // invoked, key = archetype ("Worker"/"Imp"/…)

        // ── накопленный урон за матч (для TakeDamageCondition; абсолютно по этому игроку) ──
        public int PlayerDamageTaken;          // урон ПЛЕЕРУ (любой источник)
        public int PlayerDamageTakenOwnTurn;   // урон ПЛЕЕРУ от СЕБЯ (Source==Target) ≈ на своём ходу (Вуду)
        public int CreaturesDamageTaken;       // суммарный урон СУЩЕСТВАМ этого игрока

        public int SpellsPlayed;               // разыграно ЗАКЛИНАНИЙ этим игроком («Моментум»: урон за каждый спелл)

        /// <summary>ТОКЕНЫ этого игрока, погибшие за матч (токены не идут в кладбище — Limbo, поэтому «трупы»
        /// для TierSource.Corpses = существа в кладбище + этот счётчик). DeathTrackedEvent на обоих → зеркален.</summary>
        public int TokensDied;

        /// <summary>ЖУРНАЛ заклинаний игрока в порядке розыгрыша (с повторами) — идентичности для создания
        /// копий (экзотик «разыграть все заклинания матча»). События на обоих клиентах → лог зеркален.</summary>
        public List<SpellPlayRecord> SpellsPlayedLog;

        /// <summary>ЖУРНАЛ ЧАР игрока в порядке розыгрыша (с повторами, БЕЗ токенов — те не «разыгрываются»,
        /// а токен из руки отсекает трекер по TokenTag) — идентичности для пересоздания (Мистер Постоянство:
        /// «призовите все чары, разыгранные вами в этом матче»). События на обоих клиентах → лог зеркален.</summary>
        public List<SpellPlayRecord> CharmsPlayedLog;
    }

    /// <summary>Одна запись журнала розыгрышей (заклинания/чары): идентичность для пересоздания копии (CreateCardEvent).</summary>
    public struct SpellPlayRecord
    {
        public string ExpansionId;
        public int ModelId;

        /// <summary>Сущность-исходник в момент розыгрыша (CardPlayedEvent.CardEntity, зеркальна на обоих
        /// клиентах — событие идёт на обоих так же, как остальные поля этого трекера). Нужна, чтобы
        /// пересоздание (Мистер Постоянство) могло склонировать ЖИВЫЕ способности исходника, а не только
        /// печатный шаблон по ModelId — иначе собранная из доноров чара («Проклятье для принцессы») при
        /// переигрывании возвращалась бы голой болванкой без графт-эффектов (баг 2026-08-21).
        /// Сущность могла УМЕРЕТЬ/сгореть к моменту переигрывания — тогда просто нет способностей клонировать
        /// и получаем печатный шаблон, как раньше (не хуже старого поведения).</summary>
        public int SourceEntity;
    }
}
