using System.Collections.Generic;

namespace Game.Core.Ecs.Components
{
    /// <summary>
    /// Матч-счётчики на entity игрока (инкрементит MatchCounterTrackerSystem). Измерения:
    ///   CountsByModelId     — РАЗЫГРАНО карт по ModelId (Позвать рой);
    ///   DrawnByModelId      — ВЗЯТО карт по ModelId (Вонючее облако);
    ///   GeneratedByModelId  — СОЗДАНО/ЗАМЕШАНО карт этим игроком по ModelId (Гнидальф);
    ///   InvokedByArchetype  — ПРИЗВАНО существ по ключу архетипа (Грыз: "Imp").
    /// Синк не нужен: события (CardPlayed/Drawn/Generated/CreatureInvoked) идут на обоих клиентах → счётчики зеркальны.
    /// </summary>
    public struct MatchCounterComponent
    {
        public Dictionary<int, int> CountsByModelId;       // played
        public Dictionary<int, int> DrawnByModelId;        // drawn
        public Dictionary<int, int> GeneratedByModelId;    // generated by this player
        public Dictionary<string, int> InvokedByArchetype; // invoked, key = archetype ("Worker"/"Imp"/…)

        // ── накопленный урон за матч (для TakeDamageCondition; абсолютно по этому игроку) ──
        public int PlayerDamageTaken;          // урон ПЛЕЕРУ (любой источник)
        public int PlayerDamageTakenOwnTurn;   // урон ПЛЕЕРУ от СЕБЯ (Source==Target) ≈ на своём ходу (Вуду)
        public int CreaturesDamageTaken;       // суммарный урон СУЩЕСТВАМ этого игрока
    }
}
